### ISSUE TITLE
Uncaught Exception. Crashing the entire Node-RED!!!

### ISSUE THREAD

**Issue by torinnguyen** [bartbutenaers/node-red-contrib-reverse-proxy#1]
1|node-red | 29 Mar 18:55:30 - [red] Uncaught Exception:
1|node-red | 29 Mar 18:55:30 - TypeError: First argument must be a string or Buffer
1|node-red |     at ServerResponse.end (_http_outgoing.js:742:13)
1|node-red |     at handleError (/root/.node-red/node_modules/node-red-contrib-http-proxy/http_proxy.js:27:13)
1|node-red |     at ProxyServer.<anonymous> (/root/.node-red/node_modules/node-red-contrib-http-proxy/http_proxy.js:38:13)
1|node-red |     at ProxyServer.emit (/root/.node-red/node_modules/eventemitter3/index.js:210:27)
1|node-red |     at ClientRequest.proxyError (/root/.node-red/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:163:18)
1|node-red |     at emitOne (events.js:121:20)
1|node-red |     at ClientRequest.emit (events.js:211:7)
1|node-red |     at Socket.socketErrorListener (_http_client.js:387:9)
1|node-red |     at emitOne (events.js:116:13)
1|node-red |     at Socket.emit (events.js:211:7)
1|node-red |     at emitErrorNT (internal/streams/destroy.js:64:8)
1|node-red |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
1|node-red |     at process._tickDomainCallback (internal/process/next_tick.js:218:9)

**Comment by torinnguyen** [comment]
Line 27: http_proxy.js
**err** object may not be a String or Buffer. That's the problem.
